name: CI Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  login-and-build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
      
    - name: Build the Docker image
      run: docker build -t hemanthgangula/cicd-pipeline .
      
    - name: Push to Dockerhub
      run: docker push hemanthgangula/cicd-pipeline:latest

